# Generated by Django 5.2.1 on 2025-09-19 09:05

import accounts.utils.image_upload
import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.utils.image_upload.USER_DIRECTORY_PATH, validators=[core.utils.VALIDATE_IMAGE_SIZE])),
                ('username', models.CharField(db_index=True, max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')])),
                ('slug', models.SlugField(editable=False, max_length=120, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=180, unique=True, validators=[django.core.validators.MinLengthValidator(10), core.utils.VALIDATE_EMAIL])),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), core.utils.VALIDATE_ALPHA])),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3), core.utils.VALIDATE_ALPHA])),
                ('number', models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
