version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    networks:
      - pngnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - redis
    networks:
      - pngnet

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - pngnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pngnet

networks:
  pngnet:
    driver: bridge
