export default function Privacy() {
    return (
        <section className="relative top-0 left-0 right-0 py-5 lg:py-10 w-full bg-[#FBFAFF]">
            <div className="max-w-screen-lg container mx-auto px-2.5 lg:px-5 w-full">
                <div>
                    <h1 className="text-3xl lg:text-5xl font-bold mb-5 lg:mb-8 text-center">Privacy Policy</h1>
                    <p className="md:text-sm lg:text-base text-justify">
                        At PNGPoint, your Privacy is of utmost significance to us. This Privacy Policy outlines how we collect, use, store, and cover your particular information when you visit our website or interact with our services. Please read this policy precisely to understand our practices. 1. Information We Collect When you use PNGPoint, we may collect the following information particular details like your name and dispatch when you communicate us or subscribe to updates Device information, similar as cybersurfer type, IP address, operating system operation data like runners visited, download history, and pertaining URLs Any information you freely submit via forms or feedback tools 2. How We Use Your Information The information we collect may be used to Ameliorate the content, layout, and functionality of PNGPoint shoot newsletters, updates, and promotional content( if subscribed) Respond to inquiries and give client support Examiner and dissect operation to ameliorate website performance insure website security and descry fraudulent exertion. 3. eyefuls and Tracking We use eyefuls and analogous technologies to enhance your browsing experience. eyefuls help us flash back stoner preferences and gather data to epitomize content. You can control or disable eyefuls through your cybersurfer settings. 4. Third- Party Services PNGPoint may use third- party services like Google Analytics or announcement networks to cover business or serve advertisements. These services may collect data in agreement with their own Privacy programs. We recommend reviewing those programs to understand how your data may be used by them. 5. How We cover Your Data We apply assiduity-standard security measures to guard your particular information from unauthorized access, exposure, or destruction. While no system is 100 secure, we continuously modernize our security practices to cover your data. 6. Your Privacy Rights You have the right to Request access to any particular data we hold about you Request corrections or updates to your information Unsubscribe from marketing emails or newsletters Request omission of your particular data( subject to legal scores) 7. Policy Updates We may modernize this Privacy Policy from time to time to reflect changes in law, technology, or business practices. Any updates will be posted on this runner with a revised effective date. Please check this runner regularly to stay informed. 8. communicate Us still, please communicate us at If you have any questions about this Privacy Policy or how we handle your data.
                    </p>
                </div>
            </div>
        </section>
    );
}
