#############################################################################
######### DJANGO REST FRAMEWORK DEVELOPMENT DOCKERFILE CONFIGURATION #########
#############################################################################

# PYTHON 3.12 SLIM IMAGE
FROM python:3.12-slim

# PYTHON ENVIRONMENT VARIABLES
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# SET WORKING DIRECTORY INSIDE THE CONTAINER
WORKDIR /app/backend

# RUN
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    netcat-openbsd \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# COPY REQUIREMENTS.TXT    
COPY ./requirements.txt .

# RUN
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# ADDITIONAL PYTHON PACKAGES
RUN pip install \
    daphne \
    watchfiles \
    celery \
    django-celery-beat \
    redis

# COPY APPLICATION CODE
COPY . .

# EXPOSE PORT 8000
EXPOSE 8000

# START ASGI APP WITH DAPHNE SERVER
CMD ["daphne", "-p", "8000", "-b", "0.0.0.0", "app.asgi:application"]
