# Generated by Django 5.2.1 on 2025-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('account_hash', models.CharField(max_length=255)),
                ('images_domain', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('endpoint', models.CharField(default='verify', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
