# Generated by Django 5.2.1 on 2025-09-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='keywords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.keywords'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table=None,
        ),
        migrations.AlterModelTable(
            name='keywords',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subcategories',
            table=None,
        ),
    ]
