# Generated by Django 5.2.1 on 2025-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_keywords_image_images_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='keywords',
        ),
        migrations.AddField(
            model_name='images',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.keywords'),
        ),
    ]
