# Generated by Django 5.2.1 on 2026-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_images_keywords_images_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
