# Generated by Django 5.2.1 on 2026-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_images_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='sequence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
