# Generated by Django 5.2.1 on 2026-04-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('intro_heading', models.CharField(blank=True, max_length=255)),
                ('intro_paragraph_1', models.TextField(blank=True)),
                ('intro_paragraph_2', models.TextField(blank=True)),
                ('seo_heading', models.CharField(blank=True, max_length=255)),
                ('seo_paragraph_1', models.TextField(blank=True)),
                ('seo_paragraph_2', models.TextField(blank=True)),
                ('seo_paragraph_3', models.TextField(blank=True)),
                ('popular_uses_heading', models.CharField(blank=True, max_length=255)),
                ('popular_uses', models.JSONField(blank=True, default=list)),
                ('pagination_text_template', models.TextField(blank=True, help_text="Use {page} and {name} as placeholders. E.g. You're browsing page {page} of our {name} PNG collection.")),
                ('faq_heading', models.CharField(blank=True, default='Frequently Asked Questions (FAQ)', max_length=255)),
                ('faqs', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."} objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_content', to='images.subcategories')),
            ],
        ),
    ]
