############################################################
"""
Base settings for app project.
Generated by 'django-admin startproject' using Django 5.2.3.
"""
############################################################
import os
import environ
from datetime import timedelta
from pathlib import Path

BASE_DIR = Path('/app/') \
    if '/opt/' in str(Path(__file__).resolve()) \
    else Path(__file__).resolve().parent.parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except:
    print('Cannot load dotenv variables. Is python-dotenv package installed?')

env = environ.Env()
CACHE_DEFAULT_TIMEOUT = env.int('CACHE_DEFAULT_TIMEOUT', default=300)
FRONTEND_DOMAIN = env('FRONTEND_DOMAIN', default='http://localhost:5000')
DEFAULT_CORS_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=[
        FRONTEND_DOMAIN.rstrip('/'),
        'http://localhost:5000',
        'http://127.0.0.1:5000',
    ]
)
IMAGE_UPLOAD_ALLOWED_EXTENSIONS = env.list(
    'IMAGE_UPLOAD_ALLOWED_EXTENSIONS',
    default=['.png']
)
IMAGE_UPLOAD_MAX_SIZE_MB = env.int('IMAGE_UPLOAD_MAX_SIZE_MB', default=25)
IMAGE_UPLOAD_MIN_WIDTH = env.int('IMAGE_UPLOAD_MIN_WIDTH', default=2000)
IMAGE_UPLOAD_MIN_HEIGHT = env.int('IMAGE_UPLOAD_MIN_HEIGHT', default=2000)
IMAGE_UPLOAD_MAX_WIDTH = env.int('IMAGE_UPLOAD_MAX_WIDTH', default=10000)
IMAGE_UPLOAD_MAX_HEIGHT = env.int('IMAGE_UPLOAD_MAX_HEIGHT', default=10000)
MAX_UPLOAD_REQUEST_MB = env.int('MAX_UPLOAD_REQUEST_MB', default=200)
FILE_UPLOAD_MAX_MEMORY_SIZE_MB = env.int('FILE_UPLOAD_MAX_MEMORY_SIZE_MB', default=25)
MAX_UPLOAD_IMAGES_PER_REQUEST = env.int('MAX_UPLOAD_IMAGES_PER_REQUEST', default=30)
USE_ASYNC_IMAGE_UPLOADS = env.bool('USE_ASYNC_IMAGE_UPLOADS', default=True)
TRUST_PROXY_HEADERS = env.bool('TRUST_PROXY_HEADERS', default=False)
TRUST_PROXY_IPS = env.list('TRUST_PROXY_IPS', default=[])
CLOUDFLARE_API_TOKEN = env('CLOUDFLARE_API_TOKEN', default=None)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'schema_viewer',
    'drf_spectacular',
    'drf_spectacular_sidecar',

    'configuration',
    'accounts',
    'images',
]

MIDDLEWARE = [
    'middleware.ddos_protection.DDoSProtectionMiddleware',
    'middleware.ddos_protection.RequestSizeLimitMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.ddos_protection.SecurityHeadersMiddleware',
]

DDOS_MAX_REQUESTS = env.int('DDOS_MAX_REQUESTS', default=120)
DDOS_BLOCK_DURATION = env.int('DDOS_BLOCK_DURATION', default=300)
DDOS_SUSPICIOUS_THRESHOLD = env.int('DDOS_SUSPICIOUS_THRESHOLD', default=100)

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'
ASGI_APPLICATION = 'app.asgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': env.int('DEFAULT_API_PAGE_SIZE', default=100),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '1000/minute',
        'burst': '100/second',
        'login': '50/minute',
        'register': '100/hour',
        'sustained': '1000/hour',
        'public': '600/minute',
        'token_refresh': '200/minute',
        'upload': '500/hour',
    },
}

CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = DEFAULT_CORS_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=[origin for origin in DEFAULT_CORS_ORIGINS if origin.startswith('http')]
)

SECRET_KEY = env('DJANGO_SECRET_KEY', default='dev-insecure-key-change-in-production')

SIMPLE_JWT = {
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_TOKEN_CLASSES": ('rest_framework_simplejwt.tokens.AccessToken',),
    "TOKEN_BLACKLIST_ENABLED": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "id",
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_SECURE": False,
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_SAMESITE": "Lax",
}
SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"] = timedelta(
    minutes=env.int('ACCESS_TOKEN_LIFETIME_MINUTES', default=15)
)
SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"] = timedelta(
    days=env.int('REFRESH_TOKEN_LIFETIME_DAYS', default=14)
)

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6380/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6380/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

FILE_UPLOAD_MAX_MEMORY_SIZE = min(FILE_UPLOAD_MAX_MEMORY_SIZE_MB, MAX_UPLOAD_REQUEST_MB) * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_REQUEST_MB * 1024 * 1024
REQUEST_MAX_CONTENT_LENGTH = MAX_UPLOAD_REQUEST_MB * 1024 * 1024

NEXTJS_URL = env("NEXTJS_URL", default="http://localhost:3000")
REVALIDATE_SECRET = env("REVALIDATE_SECRET", default=None)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env('REDIS_CACHE_URL', default='redis://127.0.0.1:6380/0'),
        "TIMEOUT": CACHE_DEFAULT_TIMEOUT,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "pngpoint",
    }
}

SCHEMA_VIEWER = {
    'apps': [
        'accounts',
        'images',
        'configuration',
    ],
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'images': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
